export const dependencies = {
    LoggerFactory: Symbol.for("LoggerFactory"),
    ConfigRepository: Symbol.for("ConfigRepository"),
    ConfigService: Symbol.for("ConfigService"),
    ProfileFactory: Symbol.for("ProfileFactory"),
    EdgeRepository: Symbol.for("EdgeRepository"),
    EdgeService: Symbol.for("EdgeService"),
    AssistantService: Symbol.for("AssistantService"),
    MiddlewareService: Symbol.for("MiddlewareService"),
    EdgeToolFactories: Symbol.for("EdgeToolFactories"),
    EdgeToolService: Symbol.for("EdgeToolService"),
    ProcessorFactory: Symbol.for("ProcessorFactory"),
    McpServerFactory: Symbol.for("McpServerFactory"),
    DiscoveryService: Symbol.for("DiscoveryService"),
    RestFactory: Symbol.for("RestFactory"),
    TokenRepository: Symbol.for("TokenRepository"),
    TokenService: Symbol.for("TokenService"),
} as const;
