export const dependencies = {
    LoggerService: Symbol.for("LoggerService"),
    ConfigRepository: Symbol.for("ConfigRepository"),
    ConfigService: Symbol.for("ConfigService"),
    ProfileService: Symbol.for("ProfileService"),
    EdgeRepository: Symbol.for("EdgeRepository"),
    EdgeService: Symbol.for("EdgeService"),
    AssistantRegistry: Symbol.for("AssistantRegistry"),
    AssistantService: Symbol.for("AssistantService"),
    EdgeToolMiddlewaresFactory: Symbol.for("EdgeToolMiddlewaresFactory"),
    EdgeToolFactories: Symbol.for("EdgeToolFactories"),
    EdgeToolService: Symbol.for("EdgeToolService"),
    ProcessorFactory: Symbol.for("ProcessorFactory"),
    McpServerFactory: Symbol.for("McpServerFactory"),
    MiddlewareDiscovery: Symbol.for("MiddlewareDiscovery"),
} as const;
