export const dependencies = {
    LoggerFactory: Symbol.for("LoggerFactory"),
    ConfigRepository: Symbol.for("ConfigRepository"),
    ConfigService: Symbol.for("ConfigService"),
    ProfileFactory: Symbol.for("ProfileFactory"),
    EdgeRepository: Symbol.for("EdgeRepository"),
    EdgeService: Symbol.for("EdgeService"),
    AssistantRegistry: Symbol.for("AssistantRegistry"),
    AssistantService: Symbol.for("AssistantService"),
    EdgeToolMiddlewaresFactory: Symbol.for("EdgeToolMiddlewaresFactory"),
    EdgeToolFactories: Symbol.for("EdgeToolFactories"),
    EdgeToolService: Symbol.for("EdgeToolService"),
    ProcessorFactory: Symbol.for("ProcessorFactory"),
    McpServerFactory: Symbol.for("McpServerFactory"),
    MiddlewareDiscovery: Symbol.for("MiddlewareDiscovery"),
    RestFactory: Symbol.for("RestFactory"),
    AcknowledgmentTokenRepository: Symbol.for("AcknowledgmentTokenRepository"),
    AcknowledgmentTokenService: Symbol.for("AcknowledgmentTokenService"),
} as const;
